"""Unit tests for issue reporter functionality."""

import pytest

from issue_workflow.models.branch import Branch


class TestExtractIssueNumber:
    """Tests for extracting issue number from branch name."""

    @pytest.mark.parametrize(
        "branch_name,expected",
        [
            ("feat/123-add-auth", 123),
            ("fix/456-fix-login", 456),
            ("refactor/789-cleanup", 789),
            ("docs/101-update-readme", 101),
            ("test/202-add-tests", 202),
            ("chore/303-update-deps", 303),
            # Legacy patterns
            ("feature/999-old-style", 999),
            ("bugfix/888-old-fix", 888),
            # Edge cases
            ("feat/1-single-digit", 1),
            ("feat/99999-large-number", 99999),
        ],
    )
    def test_extract_valid_patterns(self, branch_name: str, expected: int) -> None:
        """Test extracting issue number from valid branch patterns."""
        result = Branch.extract_issue_number(branch_name)
        assert result == expected

    @pytest.mark.parametrize(
        "branch_name",
        [
            "main",
            "develop",
            "release/1.0.0",
            "hotfix-123",  # Missing slash
            "feat-123",  # Missing slash
            "123-feat",  # Wrong order
            "feat/abc-no-number",  # No number
            "",  # Empty
            "feat/",  # Incomplete
        ],
    )
    def test_extract_invalid_patterns(self, branch_name: str) -> None:
        """Test that invalid patterns return None."""
        result = Branch.extract_issue_number(branch_name)
        assert result is None

    def test_extract_from_current_branch_format(self) -> None:
        """Test extraction from the branch format used by our workflow."""
        # This is the format generated by Branch.name property
        branch_name = "feat/100-implement-issue-workflow"
        result = Branch.extract_issue_number(branch_name)
        assert result == 100
